# ./docker-compose.yml
version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: costify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  web:
    build: .
    ports:
     - "8080:80"
    #image: php:7.2.2-apache
    #container_name: php_web
    #depends_on:
    #  - db
    #volumes:
    #  - . :/var/www/html/
    #ports:
    #  - "8100:80"
    #stdin_open: true
    #tty: true