version: "3"
services:
  nginx:
    container_name: lara-nginx
    image: nginx
    working_dir: /www
    ports:
      - "8088:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - .:/var/www/html
  mysql:
    container_name: lara-mysql
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: costifydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  redis:
   container_name: lara-redis
   image: redis
   ports:
     - "6379:6379"
  metabase:
    container_name: lara-metabase
#    image: metabase/metabase
#    ports:
#      - "3000:3000"